const makeString = (key, options = {}) => ({
  key,
  type: 'string',
  size: options.size ?? 255,
  required: options.required ?? false,
  default: options.default ?? null,
  array: options.array ?? false,
  format: options.format ?? null,
})

const makeEmail = (key, options = {}) => ({
  key,
  type: 'string',
  size: options.size ?? 255,
  required: options.required ?? false,
  default: options.default ?? null,
  format: 'email',
})

const makeUrl = (key, options = {}) => ({
  key,
  type: 'string',
  size: options.size ?? 2048,
  required: options.required ?? false,
  default: options.default ?? null,
  format: 'url',
})

const makeBoolean = (key, options = {}) => ({
  key,
  type: 'boolean',
  required: options.required ?? false,
  default: options.default ?? null,
})

const makeInteger = (key, options = {}) => ({
  key,
  type: 'integer',
  required: options.required ?? false,
  default: options.default ?? null,
  min: options.min ?? null,
  max: options.max ?? null,
})

const makeFloat = (key, options = {}) => ({
  key,
  type: 'double',
  required: options.required ?? false,
  default: options.default ?? null,
  min: options.min ?? null,
  max: options.max ?? null,
})

const makeDatetime = (key, options = {}) => ({
  key,
  type: 'datetime',
  required: options.required ?? false,
  default: options.default ?? null,
})

const makeEnum = (key, elements, options = {}) => ({
  key,
  type: 'enum',
  elements,
  required: options.required ?? false,
  default: options.default ?? null,
})

const makeJson = (key, options = {}) => ({
  key,
  type: 'string',
  size: options.size ?? 16000,
  required: options.required ?? false,
  default: options.default ?? null,
  format: 'json',
})

const makeRelationship = (key, target, options = {}) => ({
  key,
  type: 'relationship',
  target,
  relationType: options.relationType ?? 'one-to-many',
  onDelete: options.onDelete ?? 'cascade',
  required: options.required ?? false,
})

const baseAuditFields = [
  makeString('status', { required: true, size: 50, default: 'active' }),
  makeString('createdBy', { size: 255 }),
  makeString('updatedBy', { size: 255 }),
]

// Database ID comes from .env (APPWRITE_DATABASE_ID) or we look up by name at provision time.
// Do NOT use ID.unique() here — that generates a different random string every module load,
// making it impossible to find the same database across server restarts.
export const appwriteDatabaseConfig = {
  name: 'AfriWork',
  id: null, // Will be resolved by the provisioning script from .env or by name lookup
  description: 'Primary database for AfriWork user, work, collaboration and payments domains.',
}

export const appwriteCollectionDefinitions = [
  {
    key: '6a587e7c001fcd24af7c',
    name: 'Users',
    description: 'Core identity records for platform users.',
    attributes: [
      makeEmail('email', { required: true }),
      makeString('phone', { size: 50 }),
      makeString('fullName', { required: true, size: 150 }),
      makeString('username', { required: true, size: 80 }),
      makeUrl('avatarUrl'),
      makeEnum('role', ['talent', 'employer', 'admin', 'moderator', 'partner'], { required: true, default: 'talent' }),
      makeEnum('status', ['pending', 'active', 'suspended', 'deleted'], { required: true, default: 'pending' }),
      makeBoolean('emailVerified', { default: false }),
      makeBoolean('phoneVerified', { default: false }),
      makeBoolean('isActive', { default: true }),
      makeDatetime('lastLoginAt'),
      makeDatetime('deletedAt'),
      makeJson('metadata'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_users_email', type: 'unique', attributes: ['email'] },
      { key: 'idx_users_username', type: 'unique', attributes: ['username'] },
      { key: 'idx_users_role', type: 'key', attributes: ['role'] },
      { key: 'idx_users_status', type: 'key', attributes: ['status'] },
      { key: 'idx_users_created', type: 'key', attributes: ['$createdAt'] },
    ],
    relationships: [
      { target: 'profiles', type: 'one-to-one', sourceField: 'userId', targetField: 'userId' },
    ],
  },
  {
    key: '6a587e7c001fc8e87fb3',
    name: 'Jobs',
    description: 'Job opportunities posted by employers or organizations.',
    attributes: [
      makeString('title', { required: true, size: 200 }),
      makeString('description', { required: true, size: 8000 }),
      makeString('companyId', { size: 255 }),
      makeString('employerId', { required: true, size: 255 }),
      makeString('location', { size: 180 }),
      makeBoolean('remote', { default: false }),
      makeEnum('jobType', ['full_time', 'part_time', 'contract', 'internship', 'volunteer'], { default: 'full_time' }),
      makeEnum('experienceLevel', ['entry', 'junior', 'mid', 'senior', 'expert'], { default: 'mid' }),
      makeFloat('salaryMin', { min: 0 }),
      makeFloat('salaryMax', { min: 0 }),
      makeString('currency', { size: 10, default: 'USD' }),
      makeEnum('status', ['draft', 'active', 'closed', 'paused', 'archived'], { required: true, default: 'draft' }),
      makeDatetime('deadline'),
      makeBoolean('isFeatured', { default: false }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_jobs_employer', type: 'key', attributes: ['employerId'] },
      { key: 'idx_jobs_company', type: 'key', attributes: ['companyId'] },
      { key: 'idx_jobs_status', type: 'key', attributes: ['status'] },
      { key: 'idx_jobs_remote', type: 'key', attributes: ['remote'] },
      { key: 'idx_jobs_featured', type: 'key', attributes: ['isFeatured'] },
    ],
  },
  {
    key: '6a587e7c001fc322929f',
    name: 'Projects',
    description: 'Collaborative work projects created by users or organizations.',
    attributes: [
      makeString('title', { required: true, size: 200 }),
      makeString('description', { size: 5000 }),
      makeEnum('status', ['draft', 'active', 'paused', 'completed', 'cancelled'], { required: true, default: 'draft' }),
      makeEnum('visibility', ['private', 'team', 'public'], { required: true, default: 'private' }),
      makeString('ownerId', { required: true, size: 255 }),
      makeString('organizationId', { size: 255 }),
      makeDatetime('startDate'),
      makeDatetime('endDate'),
      makeFloat('budget', { min: 0 }),
      makeString('currency', { size: 10, default: 'USD' }),
      makeInteger('progress', { min: 0, max: 100 }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_projects_owner', type: 'key', attributes: ['ownerId'] },
      { key: 'idx_projects_org', type: 'key', attributes: ['organizationId'] },
      { key: 'idx_projects_status', type: 'key', attributes: ['status'] },
      { key: 'idx_projects_visibility', type: 'key', attributes: ['visibility'] },
    ],
  },
  {
    key: '6a587e7c001fc429b681',
    name: 'Profiles',
    description: 'Professional profile information for talent discovery and hiring.',
    attributes: [
      makeString('userId', { required: true, size: 255 }),
      makeString('headline', { required: true, size: 160 }),
      makeString('bio', { size: 4000 }),
      makeString('location', { size: 160 }),
      makeString('timezone', { size: 80 }),
      makeEnum('experienceLevel', ['entry', 'junior', 'mid', 'senior', 'expert'], { required: true, default: 'mid' }),
      makeEnum('availability', ['available', 'busy', 'unavailable'], { default: 'available' }),
      makeUrl('website'),
      makeUrl('linkedinUrl'),
      makeUrl('githubUrl'),
      makeUrl('portfolioUrl'),
      makeUrl('resumeUrl'),
      makeInteger('profileCompleteness', { min: 0, max: 100 }),
      makeBoolean('isVerified', { default: false }),
      makeEnum('verificationStatus', ['unverified', 'pending', 'verified', 'rejected'], { default: 'unverified' }),
      makeEnum('preferredWorkType', ['full_time', 'part_time', 'contract', 'remote', 'hybrid'], { default: 'remote' }),
      makeFloat('hourlyRate', { min: 0 }),
      makeString('currency', { size: 10, default: 'USD' }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_profiles_user', type: 'unique', attributes: ['userId'] },
      { key: 'idx_profiles_verified', type: 'key', attributes: ['isVerified'] },
      { key: 'idx_profiles_availability', type: 'key', attributes: ['availability'] },
      { key: 'idx_profiles_location', type: 'key', attributes: ['location'] },
    ],
  },
  {
    key: '6a587e7c001fcd315e17',
    name: 'Courses',
    description: 'Learning content, programs and training courses.',
    attributes: [
      makeString('title', { required: true, size: 220 }),
      makeString('description', { size: 8000 }),
      makeString('instructorId', { size: 255 }),
      makeString('organizationId', { size: 255 }),
      makeString('category', { size: 120 }),
      makeEnum('level', ['beginner', 'intermediate', 'advanced'], { default: 'beginner' }),
      makeBoolean('isPublished', { default: false }),
      makeUrl('thumbnailUrl'),
      makeFloat('price', { min: 0 }),
      makeString('currency', { size: 10, default: 'USD' }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_courses_instructor', type: 'key', attributes: ['instructorId'] },
      { key: 'idx_courses_org', type: 'key', attributes: ['organizationId'] },
      { key: 'idx_courses_category', type: 'key', attributes: ['category'] },
      { key: 'idx_courses_published', type: 'key', attributes: ['isPublished'] },
    ],
  },
  {
    key: '6a587e7c001fc528256d',
    name: 'Bookmarks',
    description: 'Saved jobs, projects, courses or profiles.',
    attributes: [
      makeString('userId', { required: true, size: 255 }),
      makeString('targetType', { required: true, size: 80 }),
      makeString('targetId', { required: true, size: 255 }),
      makeJson('metadata'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_bookmarks_user', type: 'key', attributes: ['userId'] },
      { key: 'idx_bookmarks_type', type: 'key', attributes: ['targetType'] },
      { key: 'idx_bookmarks_target', type: 'key', attributes: ['targetType', 'targetId'] },
      { key: 'idx_bookmarks_unique', type: 'unique', attributes: ['userId', 'targetType', 'targetId'] },
    ],
  },
  {
    key: '6a587e7c001fcb74cb91',
    name: 'Activity Logs',
    description: 'Audit and analytics activity records.',
    attributes: [
      makeString('userId', { required: true, size: 255 }),
      makeString('action', { required: true, size: 160 }),
      makeString('entityType', { size: 80 }),
      makeString('entityId', { size: 255 }),
      makeJson('metadata'),
      makeString('ipAddress', { size: 80 }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_activity_user', type: 'key', attributes: ['userId'] },
      { key: 'idx_activity_action', type: 'key', attributes: ['action'] },
      { key: 'idx_activity_entity', type: 'key', attributes: ['entityType', 'entityId'] },
    ],
  },
  {
    key: '6a587e7c001fcc0e989a',
    name: 'Teams',
    description: 'Team metadata and membership context for collaboration.',
    attributes: [
      makeString('name', { required: true, size: 160 }),
      makeString('description', { size: 4000 }),
      makeString('projectId', { required: true, size: 255 }),
      makeString('ownerId', { required: true, size: 255 }),
      makeEnum('status', ['active', 'archived', 'disabled'], { required: true, default: 'active' }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_teams_project', type: 'key', attributes: ['projectId'] },
      { key: 'idx_teams_owner', type: 'key', attributes: ['ownerId'] },
      { key: 'idx_teams_status', type: 'key', attributes: ['status'] },
    ],
  },
  {
    key: '6a587e7c001fc770fe2e',
    name: 'Applications',
    description: 'Applications submitted to jobs or projects.',
    attributes: [
      makeString('jobId', { required: true, size: 255 }),
      makeString('applicantId', { required: true, size: 255 }),
      makeString('coverLetter', { size: 8000 }),
      makeEnum('status', ['pending', 'reviewed', 'accepted', 'rejected', 'withdrawn'], { required: true, default: 'pending' }),
      makeFloat('proposedRate', { min: 0 }),
      makeString('currency', { size: 10, default: 'USD' }),
      makeDatetime('appliedAt'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_applications_job', type: 'key', attributes: ['jobId'] },
      { key: 'idx_applications_applicant', type: 'key', attributes: ['applicantId'] },
      { key: 'idx_applications_status', type: 'key', attributes: ['status'] },
      { key: 'idx_applications_unique', type: 'unique', attributes: ['jobId', 'applicantId'] },
    ],
  },
  {
    key: '6a587e7c001fccd36ce3',
    name: 'Messages',
    description: 'Direct messages and conversation content.',
    attributes: [
      makeString('conversationId', { required: true, size: 255 }),
      makeString('senderId', { required: true, size: 255 }),
      makeString('receiverId', { required: true, size: 255 }),
      makeString('content', { size: 8000 }),
      makeEnum('messageType', ['text', 'file', 'system'], { required: true, default: 'text' }),
      makeUrl('attachmentUrl'),
      makeBoolean('isRead', { default: false }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_messages_conversation', type: 'key', attributes: ['conversationId'] },
      { key: 'idx_messages_sender', type: 'key', attributes: ['senderId'] },
      { key: 'idx_messages_receiver', type: 'key', attributes: ['receiverId'] },
      { key: 'idx_messages_read', type: 'key', attributes: ['isRead'] },
    ],
  },
  {
    key: '6a587e7c001fc57cc01d',
    name: 'Notifications',
    description: 'In-app and system notifications for users.',
    attributes: [
      makeString('recipientId', { required: true, size: 255 }),
      makeString('senderId', { size: 255 }),
      makeString('type', { required: true, size: 80 }),
      makeString('title', { required: true, size: 220 }),
      makeString('body', { required: true, size: 2000 }),
      makeString('entityType', { size: 80 }),
      makeString('entityId', { size: 255 }),
      makeBoolean('isRead', { default: false }),
      makeDatetime('readAt'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_notifications_recipient', type: 'key', attributes: ['recipientId'] },
      { key: 'idx_notifications_read', type: 'key', attributes: ['isRead'] },
      { key: 'idx_notifications_type', type: 'key', attributes: ['type'] },
    ],
  },
  {
    key: '6a587e7c001fc9601e48',
    name: 'Reviews',
    description: 'Feedback and ratings for work, users or organizations.',
    attributes: [
      makeString('reviewerId', { required: true, size: 255 }),
      makeString('targetType', { required: true, size: 80 }),
      makeString('targetId', { required: true, size: 255 }),
      makeInteger('rating', { required: true, min: 1, max: 5 }),
      makeString('comment', { size: 4000 }),
      makeEnum('status', ['pending', 'approved', 'flagged', 'removed'], { required: true, default: 'pending' }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_reviews_reviewer', type: 'key', attributes: ['reviewerId'] },
      { key: 'idx_reviews_target', type: 'key', attributes: ['targetType', 'targetId'] },
      { key: 'idx_reviews_rating', type: 'key', attributes: ['rating'] },
      { key: 'idx_reviews_status', type: 'key', attributes: ['status'] },
    ],
  },
  {
    key: '6a587e7c001fc95c4ad1',
    name: 'Payments',
    description: 'Payment transactions and billing records.',
    attributes: [
      makeString('payerId', { required: true, size: 255 }),
      makeString('payeeId', { required: true, size: 255 }),
      makeFloat('amount', { required: true, min: 0 }),
      makeString('currency', { required: true, size: 10, default: 'USD' }),
      makeString('paymentMethod', { size: 80 }),
      makeEnum('status', ['pending', 'succeeded', 'failed', 'refunded'], { required: true, default: 'pending' }),
      makeString('referenceId', { size: 255 }),
      makeJson('metadata'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_payments_payer', type: 'key', attributes: ['payerId'] },
      { key: 'idx_payments_payee', type: 'key', attributes: ['payeeId'] },
      { key: 'idx_payments_status', type: 'key', attributes: ['status'] },
      { key: 'idx_payments_reference', type: 'unique', attributes: ['referenceId'] },
    ],
  },
  {
    key: '6a587e7c001fc3048623',
    name: 'Wallet',
    description: 'User wallet balances and financial state.',
    attributes: [
      makeString('userId', { required: true, size: 255 }),
      makeFloat('balance', { required: true, min: 0 }),
      makeString('currency', { required: true, size: 10, default: 'USD' }),
      makeEnum('status', ['active', 'locked', 'disabled'], { required: true, default: 'active' }),
      makeDatetime('lastTransactionAt'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_wallet_user', type: 'unique', attributes: ['userId'] },
      { key: 'idx_wallet_currency', type: 'key', attributes: ['currency'] },
      { key: 'idx_wallet_status', type: 'key', attributes: ['status'] },
    ],
  },
  {
    key: '6a587e7c001fce3acb7e',
    name: 'Certificates',
    description: 'Credential and certification records for users.',
    attributes: [
      makeString('userId', { required: true, size: 255 }),
      makeString('courseId', { size: 255 }),
      makeString('title', { required: true, size: 220 }),
      makeString('issuer', { required: true, size: 160 }),
      makeDatetime('issuedAt'),
      makeDatetime('expiresAt'),
      makeUrl('certificateUrl'),
      makeString('verificationCode', { size: 120 }),
      makeEnum('status', ['active', 'expired', 'revoked'], { required: true, default: 'active' }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_certificates_user', type: 'key', attributes: ['userId'] },
      { key: 'idx_certificates_course', type: 'key', attributes: ['courseId'] },
      { key: 'idx_certificates_code', type: 'unique', attributes: ['verificationCode'] },
      { key: 'idx_certificates_status', type: 'key', attributes: ['status'] },
    ],
  },
  {
    key: '6a587e7c001fcee69acb',
    name: 'Skills',
    description: 'Reusable skill taxonomy values.',
    attributes: [
      makeString('name', { required: true, size: 120 }),
      makeString('category', { required: true, size: 100 }),
      makeString('slug', { required: true, size: 120 }),
      makeString('description', { size: 2000 }),
      makeFloat('popularityScore', { min: 0, max: 100 }),
      makeBoolean('isActive', { default: true }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_skills_name', type: 'unique', attributes: ['name'] },
      { key: 'idx_skills_slug', type: 'unique', attributes: ['slug'] },
      { key: 'idx_skills_category', type: 'key', attributes: ['category'] },
      { key: 'idx_skills_active', type: 'key', attributes: ['isActive'] },
    ],
  },
  {
    key: '6a587e7c001fcf0d1b3e',
    name: 'Storage Bucket',
    description: 'File uploads and attachments.',
    attributes: [],
    indexes: [],
  },
  {
    key: '6a587e7c001fc24af7c',
    name: 'Task Lists',
    description: 'Kanban columns / task list groups within a project.',
    attributes: [
      makeString('projectId', { required: true, size: 255 }),
      makeString('title', { required: true, size: 200 }),
      makeString('description', { size: 2000 }),
      makeInteger('position', { required: true, min: 0 }),
      makeString('color', { size: 20, default: '#6366f1' }),
      makeEnum('status', ['active', 'archived'], { required: true, default: 'active' }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_tasklists_project', type: 'key', attributes: ['projectId'] },
      { key: 'idx_tasklists_position', type: 'key', attributes: ['position'] },
    ],
  },
  {
    key: '6a587e7c001fc24af7d',
    name: 'Tasks',
    description: 'Individual tasks within task lists. Supports backlog, Kanban, and Gantt.',
    attributes: [
      makeString('projectId', { required: true, size: 255 }),
      makeString('taskListId', { required: true, size: 255 }),
      makeString('title', { required: true, size: 300 }),
      makeString('description', { size: 10000 }),
      makeEnum('priority', ['none', 'low', 'medium', 'high', 'urgent'], { required: true, default: 'none' }),
      makeEnum('status', ['backlog', 'todo', 'in_progress', 'in_review', 'done', 'cancelled'], { required: true, default: 'todo' }),
      makeInteger('position', { required: true, min: 0 }),
      makeString('assigneeId', { size: 255 }),
      makeDatetime('dueDate'),
      makeDatetime('startDate'),
      makeFloat('estimatedHours', { min: 0 }),
      makeFloat('loggedHours', { min: 0 }),
      makeInteger('progress', { min: 0, max: 100 }),
      makeString('milestoneId', { size: 255 }),
      makeJson('labels'),
      makeJson('attachments'),
      makeInteger('commentCount', { min: 0 }),
      makeBoolean('isArchived', { default: false }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_tasks_project', type: 'key', attributes: ['projectId'] },
      { key: 'idx_tasks_tasklist', type: 'key', attributes: ['taskListId'] },
      { key: 'idx_tasks_assignee', type: 'key', attributes: ['assigneeId'] },
      { key: 'idx_tasks_priority', type: 'key', attributes: ['priority'] },
      { key: 'idx_tasks_due', type: 'key', attributes: ['dueDate'] },
      { key: 'idx_tasks_status', type: 'key', attributes: ['status'] },
      { key: 'idx_tasks_milestone', type: 'key', attributes: ['milestoneId'] },
    ],
  },
  {
    key: '6a587e7c001fc24af7e',
    name: 'Milestones',
    description: 'Project milestones for tracking major progress points.',
    attributes: [
      makeString('projectId', { required: true, size: 255 }),
      makeString('title', { required: true, size: 200 }),
      makeString('description', { size: 4000 }),
      makeDatetime('dueDate'),
      makeDatetime('completedAt'),
      makeEnum('status', ['pending', 'in_progress', 'completed', 'cancelled'], { required: true, default: 'pending' }),
      makeInteger('progress', { min: 0, max: 100 }),
      makeFloat('budget', { min: 0 }),
      makeString('currency', { size: 10, default: 'USD' }),
      makeString('completedBy', { size: 255 }),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_milestones_project', type: 'key', attributes: ['projectId'] },
      { key: 'idx_milestones_due', type: 'key', attributes: ['dueDate'] },
      { key: 'idx_milestones_status', type: 'key', attributes: ['status'] },
    ],
  },
  {
    key: '6a587e7c001fc24af7f',
    name: 'Comments',
    description: 'Comments and discussions on tasks, milestones, and projects.',
    attributes: [
      makeString('entityType', { required: true, size: 60 }),
      makeString('entityId', { required: true, size: 255 }),
      makeString('authorId', { required: true, size: 255 }),
      makeString('content', { required: true, size: 16000 }),
      makeString('parentId', { size: 255 }),
      makeJson('mentions'),
      makeJson('attachments'),
      makeBoolean('isEdited', { default: false }),
      makeDatetime('editedAt'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_comments_entity', type: 'key', attributes: ['entityType', 'entityId'] },
      { key: 'idx_comments_author', type: 'key', attributes: ['authorId'] },
      { key: 'idx_comments_parent', type: 'key', attributes: ['parentId'] },
      { key: 'idx_comments_created', type: 'key', attributes: ['$createdAt'] },
    ],
  },
  {
    key: '6a587e7c001fc24af80',
    name: 'Activity Feeds',
    description: 'Real-time chronological activity feed entries for projects.',
    attributes: [
      makeString('projectId', { required: true, size: 255 }),
      makeString('actorId', { required: true, size: 255 }),
      makeString('action', { required: true, size: 100 }),
      makeString('entityType', { size: 60 }),
      makeString('entityId', { size: 255 }),
      makeString('description', { size: 2000 }),
      makeJson('metadata'),
      ...baseAuditFields,
    ],
    indexes: [
      { key: 'idx_activityfeeds_project', type: 'key', attributes: ['projectId'] },
      { key: 'idx_activityfeeds_actor', type: 'key', attributes: ['actorId'] },
      { key: 'idx_activityfeeds_action', type: 'key', attributes: ['action'] },
      { key: 'idx_activityfeeds_created', type: 'key', attributes: ['$createdAt'] },
    ],
  },
]

// Re-exported helper functions for the provisioning script
export { makeString, makeEmail, makeUrl, makeBoolean, makeInteger, makeFloat, makeDatetime, makeEnum, makeJson, makeRelationship }
